[workspace]
resolver = "2"
members = ["host", "methods", "methods/guest_lazy_precompiles", "methods/guest_baseline", "methods/guest_baseline_precompiles", "methods/guest_dummy", "core"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
