apiVersion: batch/v1
kind: Job
metadata:
  name: create-topics
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: bitnami/kafka:latest
        env:
          - name: KAFKA_BROKER_CONNECT
            value: kafka:9092
        command:
          - /bin/sh
          - -c
          - |
            kafka-topics.sh --create --topic proofing-input --bootstrap-server $KAFKA_BROKER_CONNECT --partitions 1 --replication-factor 1 && \
            kafka-topics.sh --create --topic proofing-output --bootstrap-server $KAFKA_BROKER_CONNECT --partitions 1 --replication-factor 1
      restartPolicy: Never
  backoffLimit: 1
