apiVersion: apps/v1
kind: Deployment
metadata:
  name: proofing-service
  labels:
    app: proofing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proofing
  template:
    metadata:
      labels:
        app: proofing
    spec:
      containers:
        - name: proofing-service
          image: dein-repo/proofing-service:latest  # Hier dein Image anpassen
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
