[package]
name = "proving_service_core"
version = "0.1.0"
edition = "2021"

[build-dependencies]

[dependencies]
risc0-zkvm = { version = "^2.0.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"