[package]
name = "metrics"
version = "0.1.0"
edition = "2021"


[dependencies]
risc0-zkvm = "0.19"                                # Or the latest version you're using
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
csv = "1.3"
perf-event = "0.4"
